/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"E:\5_Working_FIOT\F2_MotionBand\MotionBand\ble_sdk_2_02_01_18\blelib\host\host_pxxx.a"
"E:\5_Working_FIOT\F2_MotionBand\MotionBand\ble_sdk_2_02_01_18\blelib\ctrl\cc2640\cc2640_ctrl_pxxx.a"
"E:\5_Working_FIOT\F2_MotionBand\MotionBand\ble_sdk_2_02_01_18\blelib\hci_tl\cc26xx\cc26xx_hci_tl_none.a"
